import React, { useContext } from "react";
import Head from "next/head";
import CommentDisplay from "../components/CommentDisplay";
import { AppContext } from "../contexts/appContext";
import { MainEl } from "../styles/shared";
import Overlay from "../components/Overlay";
import InputCard from "../components/InputCard";

export default function Home() {
  const { state, modalState } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Interactive Comment | FEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {modalState.active && <Overlay />}

      <MainEl>
        {state.map((comment) => (
          <CommentDisplay key={comment.id} comment={comment} />
        ))}

        <div>
          <InputCard />
        </div>
      </MainEl>
    </>
  );
}
